# Dependencies
highlighter:      pygments

# Setup
title:            Ye Yuan
tagline:          'Academic Webpage'
description:      'Researcher - Control Theory, Machine Learning, Systems Biology and Power Systems.'
url:              http://yy311.github.io
baseurl:          /
cover_image:  yeyuan.jpg

author:
name:           'Ye Yuan'
email:          ye.yuan@outlook.com

paginate:         6
paginate_path:    "/notes/page:num"

# List of Pages

pages_list:
  - name: Biography
    loc: /bio.html
  - name: Research
    loc: /research.html
  - name: Publications
    loc: /publication.html
  - name: Teaching
    loc: /teaching.html
  - name: Software
    loc: /software.html
  
