# Dependencies
highlighter:      pygments

# Setup
title:            Ye Yuan
tagline:          'Research and Stuff'
description:      'I am an Assistant Professor at Nanyang Technologicial University, Singapore.'
url:              http://yilinmo.github.io
baseurl:          /
cover_image: /public/zion.png

author:
name:           'Ye Yuan'
email:          ye.yuan@outlook.com

paginate:         5
paginate_path:    "/notes/page:num"

# List of Pages

pages_list:
  - name: Research
    loc: /research.html
  - name: Teaching
    loc: /teaching.html
  - name: Publication
    loc: /publication.html
  - name: Notes
    loc: /notes
